name: Build, Lint, and Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-lint-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.6]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - name: Cache snap build
        if: ${{ matrix.node-version == '18.6' }}
        uses: actions/cache@v3
        with:
          path: ./packages/snap/dist
          key: snap-${{ runner.os }}-${{ github.sha }}
